//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportSystem.Database_File
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LGNewReportingSystemEntities : DbContext
    {
        public LGNewReportingSystemEntities()
            : base("name=LGNewReportingSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brigade> Brigade { get; set; }
        public virtual DbSet<Coy> Coy { get; set; }
        public virtual DbSet<EntryType> EntryType { get; set; }
        public virtual DbSet<OrdersType> OrdersType { get; set; }
        public virtual DbSet<Rank> Rank { get; set; }
        public virtual DbSet<SoldierInfo> SoldierInfo { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
        public virtual DbSet<P2OEntry> P2OEntry { get; set; }
        public virtual DbSet<Password> Password { get; set; }
    
        public virtual int sp_CheckBrigadeExist(string brigadeName)
        {
            var brigadeNameParameter = brigadeName != null ?
                new ObjectParameter("brigadeName", brigadeName) :
                new ObjectParameter("brigadeName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CheckBrigadeExist", brigadeNameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_CheckifBrigadeExist(string brigadeName, ObjectParameter countvalue)
        {
            var brigadeNameParameter = brigadeName != null ?
                new ObjectParameter("brigadeName", brigadeName) :
                new ObjectParameter("brigadeName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_CheckifBrigadeExist", brigadeNameParameter, countvalue);
        }
    
        public virtual int sp_DeleteBrigade(Nullable<int> bdeId)
        {
            var bdeIdParameter = bdeId.HasValue ?
                new ObjectParameter("bdeId", bdeId) :
                new ObjectParameter("bdeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteBrigade", bdeIdParameter);
        }
    
        public virtual int sp_DeleteCoy(Nullable<int> unitId, Nullable<int> bdeid, Nullable<int> coyId)
        {
            var unitIdParameter = unitId.HasValue ?
                new ObjectParameter("unitId", unitId) :
                new ObjectParameter("unitId", typeof(int));
    
            var bdeidParameter = bdeid.HasValue ?
                new ObjectParameter("bdeid", bdeid) :
                new ObjectParameter("bdeid", typeof(int));
    
            var coyIdParameter = coyId.HasValue ?
                new ObjectParameter("CoyId", coyId) :
                new ObjectParameter("CoyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteCoy", unitIdParameter, bdeidParameter, coyIdParameter);
        }
    
        public virtual int sp_DeleteEntryName(Nullable<int> entryId)
        {
            var entryIdParameter = entryId.HasValue ?
                new ObjectParameter("entryId", entryId) :
                new ObjectParameter("entryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteEntryName", entryIdParameter);
        }
    
        public virtual int sp_DeleteOrderType(Nullable<int> orderId)
        {
            var orderIdParameter = orderId.HasValue ?
                new ObjectParameter("orderId", orderId) :
                new ObjectParameter("orderId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteOrderType", orderIdParameter);
        }
    
        public virtual int sp_DeletePt2Orders(Nullable<int> id, Nullable<int> rankid, Nullable<int> unitid, Nullable<int> coyid, Nullable<int> entryid, string orderno, Nullable<System.DateTime> dateofOrder, string occurrence, Nullable<System.DateTime> wef, Nullable<System.DateTime> end, string enteredby)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var rankidParameter = rankid.HasValue ?
                new ObjectParameter("rankid", rankid) :
                new ObjectParameter("rankid", typeof(int));
    
            var unitidParameter = unitid.HasValue ?
                new ObjectParameter("unitid", unitid) :
                new ObjectParameter("unitid", typeof(int));
    
            var coyidParameter = coyid.HasValue ?
                new ObjectParameter("coyid", coyid) :
                new ObjectParameter("coyid", typeof(int));
    
            var entryidParameter = entryid.HasValue ?
                new ObjectParameter("entryid", entryid) :
                new ObjectParameter("entryid", typeof(int));
    
            var ordernoParameter = orderno != null ?
                new ObjectParameter("orderno", orderno) :
                new ObjectParameter("orderno", typeof(string));
    
            var dateofOrderParameter = dateofOrder.HasValue ?
                new ObjectParameter("DateofOrder", dateofOrder) :
                new ObjectParameter("DateofOrder", typeof(System.DateTime));
    
            var occurrenceParameter = occurrence != null ?
                new ObjectParameter("Occurrence", occurrence) :
                new ObjectParameter("Occurrence", typeof(string));
    
            var wefParameter = wef.HasValue ?
                new ObjectParameter("wef", wef) :
                new ObjectParameter("wef", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            var enteredbyParameter = enteredby != null ?
                new ObjectParameter("enteredby", enteredby) :
                new ObjectParameter("enteredby", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeletePt2Orders", idParameter, rankidParameter, unitidParameter, coyidParameter, entryidParameter, ordernoParameter, dateofOrderParameter, occurrenceParameter, wefParameter, endParameter, enteredbyParameter);
        }
    
        public virtual int sp_DeleteRank(Nullable<int> rankId)
        {
            var rankIdParameter = rankId.HasValue ?
                new ObjectParameter("RankId", rankId) :
                new ObjectParameter("RankId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteRank", rankIdParameter);
        }
    
        public virtual int sp_DeleteUnit(Nullable<int> unitID, Nullable<int> bdeId)
        {
            var unitIDParameter = unitID.HasValue ?
                new ObjectParameter("unitID", unitID) :
                new ObjectParameter("unitID", typeof(int));
    
            var bdeIdParameter = bdeId.HasValue ?
                new ObjectParameter("bdeId", bdeId) :
                new ObjectParameter("bdeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteUnit", unitIDParameter, bdeIdParameter);
        }
    
        public virtual int sp_DeleteUser(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteUser", usernameParameter, passwordParameter);
        }
    
        public virtual int sp_EditCoy(Nullable<int> unitId, Nullable<int> bdeid, Nullable<int> coyId, string coyname)
        {
            var unitIdParameter = unitId.HasValue ?
                new ObjectParameter("unitId", unitId) :
                new ObjectParameter("unitId", typeof(int));
    
            var bdeidParameter = bdeid.HasValue ?
                new ObjectParameter("bdeid", bdeid) :
                new ObjectParameter("bdeid", typeof(int));
    
            var coyIdParameter = coyId.HasValue ?
                new ObjectParameter("CoyId", coyId) :
                new ObjectParameter("CoyId", typeof(int));
    
            var coynameParameter = coyname != null ?
                new ObjectParameter("Coyname", coyname) :
                new ObjectParameter("Coyname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EditCoy", unitIdParameter, bdeidParameter, coyIdParameter, coynameParameter);
        }
    
        public virtual int sp_EditPt2Orders(Nullable<int> id, Nullable<int> rankid, Nullable<int> unitid, Nullable<int> coyid, Nullable<int> entryid, string orderno, Nullable<System.DateTime> dateofOrder, string occurrence, Nullable<System.DateTime> wef, Nullable<System.DateTime> end, string enteredby)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var rankidParameter = rankid.HasValue ?
                new ObjectParameter("rankid", rankid) :
                new ObjectParameter("rankid", typeof(int));
    
            var unitidParameter = unitid.HasValue ?
                new ObjectParameter("unitid", unitid) :
                new ObjectParameter("unitid", typeof(int));
    
            var coyidParameter = coyid.HasValue ?
                new ObjectParameter("coyid", coyid) :
                new ObjectParameter("coyid", typeof(int));
    
            var entryidParameter = entryid.HasValue ?
                new ObjectParameter("entryid", entryid) :
                new ObjectParameter("entryid", typeof(int));
    
            var ordernoParameter = orderno != null ?
                new ObjectParameter("orderno", orderno) :
                new ObjectParameter("orderno", typeof(string));
    
            var dateofOrderParameter = dateofOrder.HasValue ?
                new ObjectParameter("DateofOrder", dateofOrder) :
                new ObjectParameter("DateofOrder", typeof(System.DateTime));
    
            var occurrenceParameter = occurrence != null ?
                new ObjectParameter("Occurrence", occurrence) :
                new ObjectParameter("Occurrence", typeof(string));
    
            var wefParameter = wef.HasValue ?
                new ObjectParameter("wef", wef) :
                new ObjectParameter("wef", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            var enteredbyParameter = enteredby != null ?
                new ObjectParameter("enteredby", enteredby) :
                new ObjectParameter("enteredby", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EditPt2Orders", idParameter, rankidParameter, unitidParameter, coyidParameter, entryidParameter, ordernoParameter, dateofOrderParameter, occurrenceParameter, wefParameter, endParameter, enteredbyParameter);
        }
    
        public virtual int sp_EditPt2OrdersLatest(Nullable<int> id, Nullable<int> rankid, Nullable<int> unitid, Nullable<int> coyid, Nullable<int> entryid, string orderno, Nullable<System.DateTime> dateofOrder, string occurrence, Nullable<System.DateTime> wef, Nullable<System.DateTime> end, string enteredby, Nullable<int> ordernoID, string oldorderno, Nullable<System.DateTime> oldDateofOrder)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var rankidParameter = rankid.HasValue ?
                new ObjectParameter("rankid", rankid) :
                new ObjectParameter("rankid", typeof(int));
    
            var unitidParameter = unitid.HasValue ?
                new ObjectParameter("unitid", unitid) :
                new ObjectParameter("unitid", typeof(int));
    
            var coyidParameter = coyid.HasValue ?
                new ObjectParameter("coyid", coyid) :
                new ObjectParameter("coyid", typeof(int));
    
            var entryidParameter = entryid.HasValue ?
                new ObjectParameter("entryid", entryid) :
                new ObjectParameter("entryid", typeof(int));
    
            var ordernoParameter = orderno != null ?
                new ObjectParameter("orderno", orderno) :
                new ObjectParameter("orderno", typeof(string));
    
            var dateofOrderParameter = dateofOrder.HasValue ?
                new ObjectParameter("DateofOrder", dateofOrder) :
                new ObjectParameter("DateofOrder", typeof(System.DateTime));
    
            var occurrenceParameter = occurrence != null ?
                new ObjectParameter("Occurrence", occurrence) :
                new ObjectParameter("Occurrence", typeof(string));
    
            var wefParameter = wef.HasValue ?
                new ObjectParameter("wef", wef) :
                new ObjectParameter("wef", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            var enteredbyParameter = enteredby != null ?
                new ObjectParameter("enteredby", enteredby) :
                new ObjectParameter("enteredby", typeof(string));
    
            var ordernoIDParameter = ordernoID.HasValue ?
                new ObjectParameter("ordernoID", ordernoID) :
                new ObjectParameter("ordernoID", typeof(int));
    
            var oldordernoParameter = oldorderno != null ?
                new ObjectParameter("Oldorderno", oldorderno) :
                new ObjectParameter("Oldorderno", typeof(string));
    
            var oldDateofOrderParameter = oldDateofOrder.HasValue ?
                new ObjectParameter("OldDateofOrder", oldDateofOrder) :
                new ObjectParameter("OldDateofOrder", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EditPt2OrdersLatest", idParameter, rankidParameter, unitidParameter, coyidParameter, entryidParameter, ordernoParameter, dateofOrderParameter, occurrenceParameter, wefParameter, endParameter, enteredbyParameter, ordernoIDParameter, oldordernoParameter, oldDateofOrderParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_EditPt2OrdersType(Nullable<int> id, Nullable<int> rankid, Nullable<int> unitid, Nullable<int> coyid, Nullable<int> entryid, string orderno, Nullable<System.DateTime> dateofOrder, string occurrence, Nullable<System.DateTime> wef, Nullable<System.DateTime> end, string enteredby)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var rankidParameter = rankid.HasValue ?
                new ObjectParameter("rankid", rankid) :
                new ObjectParameter("rankid", typeof(int));
    
            var unitidParameter = unitid.HasValue ?
                new ObjectParameter("unitid", unitid) :
                new ObjectParameter("unitid", typeof(int));
    
            var coyidParameter = coyid.HasValue ?
                new ObjectParameter("coyid", coyid) :
                new ObjectParameter("coyid", typeof(int));
    
            var entryidParameter = entryid.HasValue ?
                new ObjectParameter("entryid", entryid) :
                new ObjectParameter("entryid", typeof(int));
    
            var ordernoParameter = orderno != null ?
                new ObjectParameter("orderno", orderno) :
                new ObjectParameter("orderno", typeof(string));
    
            var dateofOrderParameter = dateofOrder.HasValue ?
                new ObjectParameter("DateofOrder", dateofOrder) :
                new ObjectParameter("DateofOrder", typeof(System.DateTime));
    
            var occurrenceParameter = occurrence != null ?
                new ObjectParameter("Occurrence", occurrence) :
                new ObjectParameter("Occurrence", typeof(string));
    
            var wefParameter = wef.HasValue ?
                new ObjectParameter("wef", wef) :
                new ObjectParameter("wef", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            var enteredbyParameter = enteredby != null ?
                new ObjectParameter("enteredby", enteredby) :
                new ObjectParameter("enteredby", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_EditPt2OrdersType", idParameter, rankidParameter, unitidParameter, coyidParameter, entryidParameter, ordernoParameter, dateofOrderParameter, occurrenceParameter, wefParameter, endParameter, enteredbyParameter);
        }
    
        public virtual int sp_EditUser(string userName, string userPassword, string rights, Nullable<int> brigadeLevel, Nullable<int> unitLevel, Nullable<int> coyLevel)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var userPasswordParameter = userPassword != null ?
                new ObjectParameter("UserPassword", userPassword) :
                new ObjectParameter("UserPassword", typeof(string));
    
            var rightsParameter = rights != null ?
                new ObjectParameter("Rights", rights) :
                new ObjectParameter("Rights", typeof(string));
    
            var brigadeLevelParameter = brigadeLevel.HasValue ?
                new ObjectParameter("BrigadeLevel", brigadeLevel) :
                new ObjectParameter("BrigadeLevel", typeof(int));
    
            var unitLevelParameter = unitLevel.HasValue ?
                new ObjectParameter("UnitLevel", unitLevel) :
                new ObjectParameter("UnitLevel", typeof(int));
    
            var coyLevelParameter = coyLevel.HasValue ?
                new ObjectParameter("CoyLevel", coyLevel) :
                new ObjectParameter("CoyLevel", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EditUser", userNameParameter, userPasswordParameter, rightsParameter, brigadeLevelParameter, unitLevelParameter, coyLevelParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_getCoyName(string coyNAME, string unitname)
        {
            var coyNAMEParameter = coyNAME != null ?
                new ObjectParameter("coyNAME", coyNAME) :
                new ObjectParameter("coyNAME", typeof(string));
    
            var unitnameParameter = unitname != null ?
                new ObjectParameter("unitname", unitname) :
                new ObjectParameter("unitname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_getCoyName", coyNAMEParameter, unitnameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_getEntyID(string entryName)
        {
            var entryNameParameter = entryName != null ?
                new ObjectParameter("entryName", entryName) :
                new ObjectParameter("entryName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_getEntyID", entryNameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_getorderID(string orderName)
        {
            var orderNameParameter = orderName != null ?
                new ObjectParameter("orderName", orderName) :
                new ObjectParameter("orderName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_getorderID", orderNameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_getRankName(string rankName)
        {
            var rankNameParameter = rankName != null ?
                new ObjectParameter("rankName", rankName) :
                new ObjectParameter("rankName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_getRankName", rankNameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_getUnitName(string unitName)
        {
            var unitNameParameter = unitName != null ?
                new ObjectParameter("unitName", unitName) :
                new ObjectParameter("unitName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_getUnitName", unitNameParameter);
        }
    
        public virtual int sp_InsertBrigade(string brigadeName)
        {
            var brigadeNameParameter = brigadeName != null ?
                new ObjectParameter("brigadeName", brigadeName) :
                new ObjectParameter("brigadeName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertBrigade", brigadeNameParameter);
        }
    
        public virtual int sp_InsertCoy(string coyName, Nullable<int> unitid, Nullable<int> bdeId)
        {
            var coyNameParameter = coyName != null ?
                new ObjectParameter("CoyName", coyName) :
                new ObjectParameter("CoyName", typeof(string));
    
            var unitidParameter = unitid.HasValue ?
                new ObjectParameter("Unitid", unitid) :
                new ObjectParameter("Unitid", typeof(int));
    
            var bdeIdParameter = bdeId.HasValue ?
                new ObjectParameter("bdeId", bdeId) :
                new ObjectParameter("bdeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertCoy", coyNameParameter, unitidParameter, bdeIdParameter);
        }
    
        public virtual int sp_InsertEntryName(string entryName)
        {
            var entryNameParameter = entryName != null ?
                new ObjectParameter("EntryName", entryName) :
                new ObjectParameter("EntryName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertEntryName", entryNameParameter);
        }
    
        public virtual int sp_InsertOrderType(string orderName)
        {
            var orderNameParameter = orderName != null ?
                new ObjectParameter("orderName", orderName) :
                new ObjectParameter("orderName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertOrderType", orderNameParameter);
        }
    
        public virtual int sp_InsertPt2Orders(Nullable<int> id, Nullable<int> rankid, Nullable<int> unitid, Nullable<int> coyid, Nullable<int> entryid, Nullable<int> orderid, string orderno, Nullable<System.DateTime> dateofOrder, string occurrence, Nullable<System.DateTime> wef, Nullable<System.DateTime> end, string enteredby)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var rankidParameter = rankid.HasValue ?
                new ObjectParameter("rankid", rankid) :
                new ObjectParameter("rankid", typeof(int));
    
            var unitidParameter = unitid.HasValue ?
                new ObjectParameter("unitid", unitid) :
                new ObjectParameter("unitid", typeof(int));
    
            var coyidParameter = coyid.HasValue ?
                new ObjectParameter("coyid", coyid) :
                new ObjectParameter("coyid", typeof(int));
    
            var entryidParameter = entryid.HasValue ?
                new ObjectParameter("entryid", entryid) :
                new ObjectParameter("entryid", typeof(int));
    
            var orderidParameter = orderid.HasValue ?
                new ObjectParameter("orderid", orderid) :
                new ObjectParameter("orderid", typeof(int));
    
            var ordernoParameter = orderno != null ?
                new ObjectParameter("orderno", orderno) :
                new ObjectParameter("orderno", typeof(string));
    
            var dateofOrderParameter = dateofOrder.HasValue ?
                new ObjectParameter("DateofOrder", dateofOrder) :
                new ObjectParameter("DateofOrder", typeof(System.DateTime));
    
            var occurrenceParameter = occurrence != null ?
                new ObjectParameter("Occurrence", occurrence) :
                new ObjectParameter("Occurrence", typeof(string));
    
            var wefParameter = wef.HasValue ?
                new ObjectParameter("wef", wef) :
                new ObjectParameter("wef", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            var enteredbyParameter = enteredby != null ?
                new ObjectParameter("enteredby", enteredby) :
                new ObjectParameter("enteredby", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertPt2Orders", idParameter, rankidParameter, unitidParameter, coyidParameter, entryidParameter, orderidParameter, ordernoParameter, dateofOrderParameter, occurrenceParameter, wefParameter, endParameter, enteredbyParameter);
        }
    
        public virtual int sp_InsertRank(string rankName)
        {
            var rankNameParameter = rankName != null ?
                new ObjectParameter("RankName", rankName) :
                new ObjectParameter("RankName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertRank", rankNameParameter);
        }
    
        public virtual int sp_InsertSecurityDetail(string firstrName, string lastName, string gender, string maritalStatus, Nullable<System.DateTime> dOB, Nullable<System.DateTime> dOE, Nullable<System.DateTime> rOD, string address, string parish)
        {
            var firstrNameParameter = firstrName != null ?
                new ObjectParameter("FirstrName", firstrName) :
                new ObjectParameter("FirstrName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var maritalStatusParameter = maritalStatus != null ?
                new ObjectParameter("MaritalStatus", maritalStatus) :
                new ObjectParameter("MaritalStatus", typeof(string));
    
            var dOBParameter = dOB.HasValue ?
                new ObjectParameter("DOB", dOB) :
                new ObjectParameter("DOB", typeof(System.DateTime));
    
            var dOEParameter = dOE.HasValue ?
                new ObjectParameter("DOE", dOE) :
                new ObjectParameter("DOE", typeof(System.DateTime));
    
            var rODParameter = rOD.HasValue ?
                new ObjectParameter("ROD", rOD) :
                new ObjectParameter("ROD", typeof(System.DateTime));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var parishParameter = parish != null ?
                new ObjectParameter("Parish", parish) :
                new ObjectParameter("Parish", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertSecurityDetail", firstrNameParameter, lastNameParameter, genderParameter, maritalStatusParameter, dOBParameter, dOEParameter, rODParameter, addressParameter, parishParameter);
        }
    
        public virtual int sp_InsertUnit(string unitName, Nullable<int> bdeId)
        {
            var unitNameParameter = unitName != null ?
                new ObjectParameter("UnitName", unitName) :
                new ObjectParameter("UnitName", typeof(string));
    
            var bdeIdParameter = bdeId.HasValue ?
                new ObjectParameter("bdeId", bdeId) :
                new ObjectParameter("bdeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertUnit", unitNameParameter, bdeIdParameter);
        }
    
        public virtual int sp_InsertUser(string userName, string userPassword, string rights, Nullable<int> brigadeLevel, Nullable<int> unitLevel, Nullable<int> coyLevel)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var userPasswordParameter = userPassword != null ?
                new ObjectParameter("UserPassword", userPassword) :
                new ObjectParameter("UserPassword", typeof(string));
    
            var rightsParameter = rights != null ?
                new ObjectParameter("Rights", rights) :
                new ObjectParameter("Rights", typeof(string));
    
            var brigadeLevelParameter = brigadeLevel.HasValue ?
                new ObjectParameter("BrigadeLevel", brigadeLevel) :
                new ObjectParameter("BrigadeLevel", typeof(int));
    
            var unitLevelParameter = unitLevel.HasValue ?
                new ObjectParameter("UnitLevel", unitLevel) :
                new ObjectParameter("UnitLevel", typeof(int));
    
            var coyLevelParameter = coyLevel.HasValue ?
                new ObjectParameter("CoyLevel", coyLevel) :
                new ObjectParameter("CoyLevel", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertUser", userNameParameter, userPasswordParameter, rightsParameter, brigadeLevelParameter, unitLevelParameter, coyLevelParameter);
        }
    
        public virtual ObjectResult<sp_SearchEmployeeInfoID_Result> sp_SearchEmployeeInfoID(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SearchEmployeeInfoID_Result>("sp_SearchEmployeeInfoID", idParameter);
        }
    
        public virtual ObjectResult<sp_SearchSecurityDetail_Result> sp_SearchSecurityDetail(string lastName)
        {
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SearchSecurityDetail_Result>("sp_SearchSecurityDetail", lastNameParameter);
        }
    
        public virtual ObjectResult<sp_selectBrigade_Result> sp_selectBrigade()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_selectBrigade_Result>("sp_selectBrigade");
        }
    
        public virtual ObjectResult<sp_selectBrigadebyBde_Result> sp_selectBrigadebyBde(Nullable<int> bdeId)
        {
            var bdeIdParameter = bdeId.HasValue ?
                new ObjectParameter("BdeId", bdeId) :
                new ObjectParameter("BdeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_selectBrigadebyBde_Result>("sp_selectBrigadebyBde", bdeIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_selectbrigadeID(Nullable<int> unitId, Nullable<int> coyID)
        {
            var unitIdParameter = unitId.HasValue ?
                new ObjectParameter("unitId", unitId) :
                new ObjectParameter("unitId", typeof(int));
    
            var coyIDParameter = coyID.HasValue ?
                new ObjectParameter("coyID", coyID) :
                new ObjectParameter("coyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_selectbrigadeID", unitIdParameter, coyIDParameter);
        }
    
        public virtual ObjectResult<sp_selectCoy_Result> sp_selectCoy(Nullable<int> bdeID, Nullable<int> unitId)
        {
            var bdeIDParameter = bdeID.HasValue ?
                new ObjectParameter("BdeID", bdeID) :
                new ObjectParameter("BdeID", typeof(int));
    
            var unitIdParameter = unitId.HasValue ?
                new ObjectParameter("unitId", unitId) :
                new ObjectParameter("unitId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_selectCoy_Result>("sp_selectCoy", bdeIDParameter, unitIdParameter);
        }
    
        public virtual ObjectResult<sp_selectCoybyID_Result> sp_selectCoybyID(Nullable<int> unitId, Nullable<int> bdeid, Nullable<int> coyID)
        {
            var unitIdParameter = unitId.HasValue ?
                new ObjectParameter("unitId", unitId) :
                new ObjectParameter("unitId", typeof(int));
    
            var bdeidParameter = bdeid.HasValue ?
                new ObjectParameter("bdeid", bdeid) :
                new ObjectParameter("bdeid", typeof(int));
    
            var coyIDParameter = coyID.HasValue ?
                new ObjectParameter("coyID", coyID) :
                new ObjectParameter("coyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_selectCoybyID_Result>("sp_selectCoybyID", unitIdParameter, bdeidParameter, coyIDParameter);
        }
    
        public virtual ObjectResult<sp_selectEntryName_Result> sp_selectEntryName()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_selectEntryName_Result>("sp_selectEntryName");
        }
    
        public virtual ObjectResult<sp_selectOrdersType_Result> sp_selectOrdersType()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_selectOrdersType_Result>("sp_selectOrdersType");
        }
    
        public virtual ObjectResult<sp_selectP20EntrybyID_Result> sp_selectP20EntrybyID(Nullable<int> regNo)
        {
            var regNoParameter = regNo.HasValue ?
                new ObjectParameter("RegNo", regNo) :
                new ObjectParameter("RegNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_selectP20EntrybyID_Result>("sp_selectP20EntrybyID", regNoParameter);
        }
    
        public virtual ObjectResult<sp_selectRank_Result> sp_selectRank()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_selectRank_Result>("sp_selectRank");
        }
    
        public virtual ObjectResult<sp_selectUnit_Result> sp_selectUnit(Nullable<int> bdeID)
        {
            var bdeIDParameter = bdeID.HasValue ?
                new ObjectParameter("BdeID", bdeID) :
                new ObjectParameter("BdeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_selectUnit_Result>("sp_selectUnit", bdeIDParameter);
        }
    
        public virtual ObjectResult<sp_selectUnitbyID_Result> sp_selectUnitbyID(Nullable<int> bdeID, Nullable<int> unitID)
        {
            var bdeIDParameter = bdeID.HasValue ?
                new ObjectParameter("BdeID", bdeID) :
                new ObjectParameter("BdeID", typeof(int));
    
            var unitIDParameter = unitID.HasValue ?
                new ObjectParameter("UnitID", unitID) :
                new ObjectParameter("UnitID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_selectUnitbyID_Result>("sp_selectUnitbyID", bdeIDParameter, unitIDParameter);
        }
    
        public virtual ObjectResult<sp_SelectUser_Result> sp_SelectUser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SelectUser_Result>("sp_SelectUser");
        }
    
        public virtual ObjectResult<Nullable<int>> sp_selectUserLogin(string userName, string password)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_selectUserLogin", userNameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<sp_selectUserLoginDetail_Result> sp_selectUserLoginDetail(string userName)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_selectUserLoginDetail_Result>("sp_selectUserLoginDetail", userNameParameter);
        }
    
        public virtual int sp_UpdateBrigade(string brigadeName, Nullable<int> bdeId)
        {
            var brigadeNameParameter = brigadeName != null ?
                new ObjectParameter("brigadeName", brigadeName) :
                new ObjectParameter("brigadeName", typeof(string));
    
            var bdeIdParameter = bdeId.HasValue ?
                new ObjectParameter("bdeId", bdeId) :
                new ObjectParameter("bdeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateBrigade", brigadeNameParameter, bdeIdParameter);
        }
    
        public virtual int sp_UpdateCoy(string coyName, Nullable<int> unitid, Nullable<int> coyid, Nullable<int> bdeId)
        {
            var coyNameParameter = coyName != null ?
                new ObjectParameter("CoyName", coyName) :
                new ObjectParameter("CoyName", typeof(string));
    
            var unitidParameter = unitid.HasValue ?
                new ObjectParameter("Unitid", unitid) :
                new ObjectParameter("Unitid", typeof(int));
    
            var coyidParameter = coyid.HasValue ?
                new ObjectParameter("Coyid", coyid) :
                new ObjectParameter("Coyid", typeof(int));
    
            var bdeIdParameter = bdeId.HasValue ?
                new ObjectParameter("bdeId", bdeId) :
                new ObjectParameter("bdeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateCoy", coyNameParameter, unitidParameter, coyidParameter, bdeIdParameter);
        }
    
        public virtual int sp_UpdateEntryName(string entryName, Nullable<int> entryId)
        {
            var entryNameParameter = entryName != null ?
                new ObjectParameter("entryName", entryName) :
                new ObjectParameter("entryName", typeof(string));
    
            var entryIdParameter = entryId.HasValue ?
                new ObjectParameter("entryId", entryId) :
                new ObjectParameter("entryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateEntryName", entryNameParameter, entryIdParameter);
        }
    
        public virtual int sp_UpdateOrderType(string orderName, Nullable<int> orderId)
        {
            var orderNameParameter = orderName != null ?
                new ObjectParameter("orderName", orderName) :
                new ObjectParameter("orderName", typeof(string));
    
            var orderIdParameter = orderId.HasValue ?
                new ObjectParameter("orderId", orderId) :
                new ObjectParameter("orderId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateOrderType", orderNameParameter, orderIdParameter);
        }
    
        public virtual int sp_UpdateRank(string rankName, Nullable<int> rankId)
        {
            var rankNameParameter = rankName != null ?
                new ObjectParameter("RankName", rankName) :
                new ObjectParameter("RankName", typeof(string));
    
            var rankIdParameter = rankId.HasValue ?
                new ObjectParameter("RankId", rankId) :
                new ObjectParameter("RankId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateRank", rankNameParameter, rankIdParameter);
        }
    
        public virtual int sp_UpdateSecurityDetail(Nullable<int> iDNum, string firstrName, string lastName, string gender, string maritalStatus, Nullable<System.DateTime> dOB, Nullable<System.DateTime> dOE, Nullable<System.DateTime> rOD, string address, string parish)
        {
            var iDNumParameter = iDNum.HasValue ?
                new ObjectParameter("IDNum", iDNum) :
                new ObjectParameter("IDNum", typeof(int));
    
            var firstrNameParameter = firstrName != null ?
                new ObjectParameter("FirstrName", firstrName) :
                new ObjectParameter("FirstrName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var maritalStatusParameter = maritalStatus != null ?
                new ObjectParameter("MaritalStatus", maritalStatus) :
                new ObjectParameter("MaritalStatus", typeof(string));
    
            var dOBParameter = dOB.HasValue ?
                new ObjectParameter("DOB", dOB) :
                new ObjectParameter("DOB", typeof(System.DateTime));
    
            var dOEParameter = dOE.HasValue ?
                new ObjectParameter("DOE", dOE) :
                new ObjectParameter("DOE", typeof(System.DateTime));
    
            var rODParameter = rOD.HasValue ?
                new ObjectParameter("ROD", rOD) :
                new ObjectParameter("ROD", typeof(System.DateTime));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var parishParameter = parish != null ?
                new ObjectParameter("Parish", parish) :
                new ObjectParameter("Parish", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateSecurityDetail", iDNumParameter, firstrNameParameter, lastNameParameter, genderParameter, maritalStatusParameter, dOBParameter, dOEParameter, rODParameter, addressParameter, parishParameter);
        }
    
        public virtual int sp_UpdateUnit(Nullable<int> unitId, string unitName, Nullable<int> bdeId)
        {
            var unitIdParameter = unitId.HasValue ?
                new ObjectParameter("UnitId", unitId) :
                new ObjectParameter("UnitId", typeof(int));
    
            var unitNameParameter = unitName != null ?
                new ObjectParameter("UnitName", unitName) :
                new ObjectParameter("UnitName", typeof(string));
    
            var bdeIdParameter = bdeId.HasValue ?
                new ObjectParameter("bdeId", bdeId) :
                new ObjectParameter("bdeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateUnit", unitIdParameter, unitNameParameter, bdeIdParameter);
        }
    }
}
