//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportSystem.Database_File
{
    using System;
    using System.Collections.Generic;
    
    public partial class P2OEntry
    {
        public int RegNo { get; set; }
        public int RankId { get; set; }
        public int UnitID { get; set; }
        public int CoyID { get; set; }
        public int EntryID { get; set; }
        public int OrdersID { get; set; }
        public string OrderNumber { get; set; }
        public System.DateTime DateofOrder { get; set; }
        public string Occurrence { get; set; }
        public System.DateTime wefDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string EnteredBy { get; set; }
    
        public virtual Coy Coy { get; set; }
        public virtual EntryType EntryType { get; set; }
        public virtual OrdersType OrdersType { get; set; }
        public virtual Rank Rank { get; set; }
        public virtual SoldierInfo SoldierInfo { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
